In [ ]:
import stanza    
stanza.download('en') # download English model
nlp = stanza.Pipeline('en') # initialize English neural pipeline

In [1]:
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('../datasets/2018-EI-oc-En-fear-dev.txt', sep="\t", header=None, skiprows=1)

'''
li = []
all_files= {'../datasets/2018-EI-oc-En-joy-dev.txt', '../datasets/2018-EI-oc-En-sadness-dev.txt', '../datasets/2018-EI-oc-En-anger-dev.txt', '../datasets/2018-EI-oc-En-fear-dev.txt'}

for filename in all_files:
    df = pd.read_csv(filename, sep="\t", header=None, skiprows=1)
    li.append(df)

dataset = pd.concat(li, axis=0, ignore_index=True)
'''
dataset.columns = ['date', 'text', 'emotion', 'level']
dataset= dataset.sample(frac=1)


In [2]:
import re
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
import emoji
from nltk.stem import WordNetLemmatizer 
  
lemmatizer = WordNetLemmatizer() 

corpus = []
ps = PorterStemmer()

for index, row in dataset.iterrows():
    tweet = row['text']

    #handle users
    tweet = re.sub('@.*', '@user', tweet) 

    
    
    tweet = tweet.split()
    #tweet = nltk.word_tokenize(tweet)

    # stemming and stop word removal
    tweet = ' '.join([lemmatizer.lemmatize(w) for w in tweet if not w in set(stopwords.words('english'))])
    

    #tweet = nlp(tweet) # run annotation over a sentence
    
    
    #emojis
    tweet = emoji.demojize(tweet)
    
    corpus.append(tweet)

print(corpus)


ng 50yr mark awhile ago–I know #horrific damage #planet occur 'natural' #death.", 'Africa unique tremendous problem war, overpopulation, starvation tribalism make moving Africa forward hard.', '@user', '@user', 'Something #awestruck today laughing non subtitle korean variety show...', '@user', '@user', 'Wtf shawty as :face_with_steam_from_nose:', '@user', "There's nothing interesting besides retweet follow #annoyed :persevering_face::persevering_face:", 'I woke still hardly believing happened last night :anxious_face_with_sweat:', 'Hey @user', "Can't believe Zain starting secondary year :crying_face:", '@user', 'I literally love Paul much #BB19 #pissed :face_with_tears_of_joy:', '#World know difference #drunk #sober? One word. #Coherence.', 'This people like Saleem Sheikh humanity win terrorism n hatred #AmarnathYatraAttacked', 'Just watching #Phoenix video first time. Holy fuck, guy seriously deranged, unhinged. Why everyone #terrified?', 'How come quiet well behaved cat dog ride plan

In [3]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer=TfidfVectorizer(use_idf=True)
tfidf_vectorizer_vectors=tfidf_vectorizer.fit_transform(corpus)

print(tfidf_vectorizer_vectors)

(0, 1281)	0.32158820001784094
  (0, 1274)	0.32158820001784094
  (0, 1066)	0.32158820001784094
  (0, 2620)	0.32158820001784094
  (0, 2416)	0.2827980059586843
  (0, 1364)	0.32158820001784094
  (0, 654)	0.32158820001784094
  (0, 1312)	0.3044232657010189
  (0, 657)	0.32158820001784094
  (0, 1901)	0.32158820001784094
  (1, 1110)	0.2105456694613085
  (1, 2342)	0.22171309039165765
  (1, 21)	0.23866725225620697
  (1, 2546)	0.21566188809978248
  (1, 20)	0.23866725225620697
  (1, 1688)	0.21566188809978248
  (1, 2289)	0.2291191634467254
  (1, 464)	0.2291191634467254
  (1, 1175)	0.2105456694613085
  (1, 2426)	0.23866725225620697
  (1, 22)	0.2291191634467254
  (1, 1502)	0.2105456694613085
  (1, 1537)	0.19554440759857436
  (1, 1067)	0.23866725225620697
  (1, 2879)	0.4582383268934508
  :	:
  (1459, 2795)	0.4588129914497841
  (1459, 360)	0.5290325181166741
  (1459, 1665)	0.42279447545993915
  (1460, 2699)	1.0
  (1461, 2625)	0.275690204712694
  (1461, 1832)	0.275690204712694
  (1461, 2677)	0.2756902047

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

vectorizer = CountVectorizer(max_features = 1500)
#X = vectorizer.fit_transform(corpus).toarray()
X = tfidf_vectorizer_vectors.toarray()
y = []
for index, row in dataset.iterrows():
    '''
    if(int(row['level'][0])==3):
        y.append(2) 
    elif(int(row['level'][0])>0):
        y.append(1) 
    else:
        y.append(0)
    '''
    y.append(int(row['level'][0]))
y = np.array(y)
#print(vectorizer.get_feature_names())
#print(type(X[0]), y.shape)

In [5]:
'''
from nltk.featstruct import FeatStruct

X = []
i=0

for index, row in dataset.iterrows():
    element= []
    element.append(tfidf_vectorizer_vectors[i].toarray())
    element.append(np.array([0 if i !=len(row['text']) else 1 for i in range(500)]))
    element=np.array(element)
    element=element.flatten()
    X.append(element)
    i+=1
    fs1 = FeatStruct(tdidf=tfidf_vectorizer_vectors[i], size=[0 if i !=len(row['text']) else 1 for i in range(500)])
    X.append(fs1)
X=np.array(X)
print(X.shape)
'''

"\nfrom nltk.featstruct import FeatStruct\n\nX = []\ni=0\n\nfor index, row in dataset.iterrows():\n    element= []\n    element.append(tfidf_vectorizer_vectors[i].toarray())\n    element.append(np.array([0 if i !=len(row['text']) else 1 for i in range(500)]))\n    element=np.array(element)\n    element=element.flatten()\n    X.append(element)\n    i+=1\n    fs1 = FeatStruct(tdidf=tfidf_vectorizer_vectors[i], size=[0 if i !=len(row['text']) else 1 for i in range(500)])\n    X.append(fs1)\nX=np.array(X)\nprint(X.shape)\n"

In [6]:
# Split dataset into training and test sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(1171, 2887) (1171,)
(293, 2887) (293,)


In [7]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Precision: ', precision_score(y_test, y_pred, average='weighted'))
print('Recall: ', recall_score(y_test, y_pred, average='weighted'))
print('F1: ', f1_score(y_test, y_pred, average='weighted'))

[[59 12 11 48]
 [ 9  6 10 35]
 [ 9 11 13 28]
 [ 9  6 10 17]]
Accuracy:  0.3242320819112628
Precision:  0.42004304802071496
Recall:  0.3242320819112628
F1:  0.34847176720717227


In [8]:
# SVM

from sklearn.svm import SVC

classifier = SVC()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Precision: ', precision_score(y_test, y_pred, average='weighted'))
print('Recall: ', recall_score(y_test, y_pred, average='weighted'))
print('F1: ', f1_score(y_test, y_pred, average='weighted'))

[[118   6   6   0]
 [ 51   2   5   2]
 [ 49   1   9   2]
 [ 32   2   7   1]]
Accuracy:  0.44368600682593856
Precision:  0.34471817147585065
Recall:  0.44368600682593856
F1:  0.3357734831577814


In [9]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Precision: ', precision_score(y_test, y_pred, average='weighted'))
print('Recall: ', recall_score(y_test, y_pred, average='weighted'))
print('F1: ', f1_score(y_test, y_pred, average='weighted'))

[[121   5   4   0]
 [ 52   2   4   2]
 [ 51   1   8   1]
 [ 34   2   6   0]]
Accuracy:  0.447098976109215
Precision:  0.32474679327604167
Recall:  0.447098976109215
F1:  0.3285668320817538


In [10]:
# Perceptron
from sklearn.linear_model import Perceptron

classifier = Perceptron() 
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test, y_pred)) 
print('Accuracy: ', accuracy_score(y_test, y_pred)) 
print('Precision: ', precision_score(y_test, y_pred, average='weighted')) 
print('Recall: ', recall_score(y_test, y_pred, average='weighted')) 
print('F1: ', f1_score(y_test, y_pred, average='weighted'))

[[64  8 57  1]
 [17  2 37  4]
 [15  1 40  5]
 [ 4  2 34  2]]
Accuracy:  0.36860068259385664
Precision:  0.38892347697808444
Recall:  0.36860068259385664
F1:  0.34149028020159256


In [11]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Precision: ', precision_score(y_test, y_pred, average='weighted'))
print('Recall: ', recall_score(y_test, y_pred, average='weighted'))
print('F1: ', f1_score(y_test, y_pred, average='weighted'))

[[111  12   6   1]
 [ 40   7   8   5]
 [ 43   6   8   4]
 [ 19   3  14   6]]
Accuracy:  0.45051194539249145
Precision:  0.3824301516341126
Recall:  0.45051194539249145
F1:  0.3837437101670087


In [12]:
# Random Forest

from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Precision: ', precision_score(y_test, y_pred, average='weighted'))
print('Recall: ', recall_score(y_test, y_pred, average='weighted'))
print('F1: ', f1_score(y_test, y_pred, average='weighted'))

[[118   6   6   0]
 [ 49   2   6   3]
 [ 44   5   7   5]
 [ 29   3   9   1]]
Accuracy:  0.43686006825938567
Precision:  0.3117178612059158
Recall:  0.43686006825938567
F1:  0.3321480481135425


In [13]:
# Simple test

import os
import numpy as np

tweet = input("Enter tweet: ")
tweet = re.sub('[^a-zA-Z]', ' ', rev).split()
tweet = ' '.join([ps.stem(w) for w in tweet])
X = vectorizer.transform([tweet]).toarray()

print(X.shape)
print(X)

print("Sentiment level: ", classifier.predict(X))

NameError: name 'rev' is not defined